name: End-to-tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm run test -- --record --key 4f04c862-cac0-4d4e-b917-056a797a9284
        uses: cypress-io/github-action@v6