name: End-to-tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    env:
      CYPRESS_USERNAME: ${{  secrets.CYPRESS_USERNAME_HRM  }}
      CYPRESS_PASSWORD: ${{  secrets.CYPRESS_PASSWORD_HRM  }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm run test -- --record --key e714ce47-c05c-4fc9-b929-4e15a5c6e460
        uses: cypress-io/github-action@v6

      