name: End-to-tests
on: push
env:
  CYPRESS_USERNAME: 'CYPRESS_USERNAME_HRM'
  CYPRESS_PASSWORD: 'CYPRESS_PASSWORD_HRM'
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6

      